{% set name = "types-tqdm" %}
{% set version = "4.66.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9553a5e44c1d485fce19f505b8bd65c0c3e87e870678d1f2ed764ae59a55d45f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f $SP_DIR/tqdm-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\tqdm-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for tqdm
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed/tree/main/stubs/tqdm

extra:
  recipe-maintainers:
    - sobolevn
    - Ubadub
